### ISSUE TITLE
GPL code

### ISSUE THREAD

**Issue by teliot** [riverbed/steelscript-vm-config#1]
looking for the riverbed Linux and GNU source for the compiled code included with my riverbed server.

**Comment by mgarabed** [comment]
@teliot -

If you are referring to one of Riverbed's commercial products, you want to look at https://support.riverbed.com for the specific Riverbed product you are interested in.  The software licenses and any applicable references can be found there.

**Comment by teliot** [comment]
was unable to find them there.

**Comment by mgarabed** [comment]
Okay, unfortunately this isn't the right forum to address that issue.  Please file a case via Riverbed's support site or ask in the Splash forum for the specific product of interest here: https://splash.riverbed.com/
