### ISSUE TITLE
cook.lab.nbttech.com is not resolved

### ISSUE THREAD

**Issue by marwanabdelhadi** [riverbed/steelscript-vm-config#2]
Hello,

Please i need your help to fix this issue as cook.lab.nbttech.com is not resolved to IP address.

Best Regards,
Marwan

**Comment by djvernon68** [comment]
Are you attempting to build your own version of the Steelscript VM? I am trying to understand why you are wanting to duplicate our internal VM build system. You can download the most current steelscript VM @ https://support.riverbed.com/bin/support/download?sid=bb8cq0p5hl7hg7fdkfil0spvbi

Checksum is: https://support.riverbed.com/bin/support/download?cid=bb8cq0p5hl7hg7fdkfil0spvbi

**Comment by marwanabdelhadi** [comment]
I always use the SteelScript OVA but this time i need to create my own virtual machine from scratch this is the policy of the current environment. right now I am stuck in this 
step 5
Provision a new Vagrant VM:
$ vagrant up

Error is as following:

steelscript_vm_1_2: Downloading: http://cook.lab.nbttech.com/downloads/vagrant/steelscript-base-os.json
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't resolve host 'cook.lab.nbttech.com'

**Comment by djvernon68** [comment]
In that case you will have to build a base Vagrant OS build and host it somewhere in your current environment. I would suggest starting with Satoshi Matsumoto's excellent packer-templates project as a way to automate the base OS build. The URL to that repo is https://github.com/kaorimatz/packer-templates

I think your best bet would be to start off with a centos-7.4 based build. One other change we include in our configuration is that we build a RPM for the latest wireshark and include that.

**Comment by marwanabdelhadi** [comment]
Thanks David
